

trigger:
- master

pool:
  vmImage: ubuntu-latest
stages:
- stage: Build
  jobs:
  - job: FirstJob
    steps:
    - bash: echo Build FirstJob
    - bash: echo $(PipelineLevelVariable)
  - job: SecondJob
    steps:
    - bash: echo Build SecondJob

- stage: DevDeploy
  environments:
    variable: Dev
  dependsOn: Build
  jobs:
  - job: DevDeployJob
    steps:
    - bash: echo $(environment)DeployJob
- stage: QADeploy
  environments:
    variable: Dev
  dependsOn: Build
  jobs:
  - job: QADeployJob
    steps:
    - bash: echo $(environment)DeployJob
- stage: PRODDeploy
  environments:
    variable: Dev
  dependsOn:
  - DevDeploy
  - QADeploy
  jobs:
  - job: PRODDeployJob
    steps:
    - bash: echo $(environment)DeployJob
